environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_GEN: Visual Studio 15 2017

install:
  - git clone https://github.com/HDFGroup/hdf5.git && cd hdf5 && git checkout hdf5-1_10_2
  - mkdir build && cd build
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\hdf5 -DBUILD_TESTING=OFF -DHDF5_BUILD_TOOLS=OFF -DHDF5_BUILD_EXAMPLES=OFF ..
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - appveyor-retry appveyor DownloadFile https://files.salome-platform.org/Salome/other/med-4.1.1.tar.gz
  - 7z x med-4.1.1.tar.gz > nul
  - 7z x med-4.1.1.tar -oC:\Libraries > nul
  - pushd C:\Libraries\med-4.1.1_SRC
  - mkdir build && cd build
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\med -DHDF5_ROOT_DIR="C:\Libraries\hdf5" -DMEDFILE_BUILD_TESTS=OFF -DMEDFILE_INSTALL_DOC=OFF ..
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone https://git.salome-platform.org/gitpub/tools/configuration.git C:\Libraries\configuration

build_script:
  - mkdir build && cd build
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=%CD:\=/%/install -DCONFIGURATION_ROOT_DIR="C:\Libraries\configuration" -DMEDFILE_ROOT_DIR="C:\Libraries\med" -DHDF5_ROOT_DIR="C:\Libraries\hdf5" -DMEDCOUPLING_ENABLE_PARTITIONER=OFF -DMEDCOUPLING_PARTITIONER_METIS=OFF -DMEDCOUPLING_PARTITIONER_SCOTCH=OFF -DSALOME_BUILD_TESTS=OFF -DMEDCOUPLING_BUILD_TESTS=OFF -DBOOST_ROOT_DIR="C:/Libraries/boost_1_69_0" -DMEDCOUPLING_ENABLE_PYTHON=OFF -DMEDCOUPLING_BUILD_DOC=OFF -DCMAKE_CXX_FLAGS="/wd4661" ..
  - cmake --build . --config Release --target install
